DATASET:
  NAME: "vg"
  MODE: "benchmark"
  PATH: "datasets/vg_bm"
  TRAIN_BATCH_SIZE: 2
  TEST_BATCH_SIZE: 1
MODEL:
  WEIGHT_IMG: "catalog://ImageNetPretrained/MSRA/R-101"
  WEIGHT_DET: ""
  ALGORITHM: "faster_rcnn"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    NUM_CLASSES: 151
  ROI_RELATION_HEAD:
    NUM_CLASSES: 51
SOLVER:
  BASE_LR: 5e-3
  MAX_ITER: 100000
  STEPS: (70000,90000)
  CHECKPOINT_PERIOD: 5000
